name: Build and test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.2.5
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm run lint
      - run: pnpm run check-format
      - run: pnpm run build
