name: Build and test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v4.1.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm run lint
      - run: pnpm run check-format
      - run: pnpm run build
